### ISSUE TITLE
Japanese translations for "Shipped" and "Salesperson association" are unnatural

### ISSUE THREAD

**Issue by nozokada** [AdobeDocs/marketo.ja-JP#1]
Issue in ./help/marketo/release-notes/current.md

Hi, could we possibly either train the MT engine or post edit the page to fix them? Let me know if you need anything else. 

**Shipped**
Actual: 発送済み
Expected: リリース済み

**Salesperson association**
Actual: 販売員協会
Expected: 営業担当者との紐づけ

![image](https://user-images.githubusercontent.com/2498905/201565295-f7fa7db0-1dd0-4a76-9c6d-f346c22907a7.png)

**Comment by mak-adobe** [comment]
@nozokada ありがとうございます。調査を開始しました。

**Comment by mak-adobe** [comment]
@nozokada G11N-11107とG11N-11108のチケットで対応中です。

**Comment by nozokada** [comment]
@mak-adobe ありがとうございます！

**Comment by mak-adobe** [comment]
@nozokada まず「発送済み」→「リリース済み」の修正が完了しました。
https://experienceleague.adobe.com/docs/marketo/using/release-notes/current.html?lang=ja

「販売員協会」は修正が進行中です。
