### ISSUE TITLE
翻訳エラー：Dynacmic Chat is DNT instead of 動的チャット

### ISSUE THREAD

**Issue by mkawachi** [AdobeDocs/marketo.ja-JP#10]
Issue in ./help/marketo/product-docs/demand-generation/dynamic-chat/dynamic-chat-overview.md

Dynamic Chat は「動的チャット」ではなくDNT、翻訳しない用語と判断されたと記憶しています。
このページだけではなく、機能名のDynamic ChatはDynamic Chatに修正をお願いします。

**Comment by mak-adobe** [comment]
@mkawachi はい、DNTになりました。リンクされたいくつかのページをまとめてG11N-13002のチケットで対応を開始しました。

**Comment by mkawachi** [comment]
ありがとうございます。よろしくお願いします。

**Comment by mak-adobe** [comment]
@mkawachi 修正が完了しました。ご協力ありがとうございました。
