### ISSUE TITLE
Consideration of adjusting the release date

### ISSUE THREAD

**Issue by kaketari** [AdobeDocs/marketo.ja-JP#11]
Issue in ./help/marketo/release-notes/release-schedule.md

https://experienceleague.adobe.com/docs/marketo/using/release-notes/release-schedule.html?lang=en
https://experienceleague.adobe.com/docs/marketo/using/release-notes/release-schedule.html?lang=ja

The 'Release Date' of July release is listed as 'July 21, 2023', but the actual release will be rolled out on 7/22 (JST) because of the time difference between Japan time and server time.
Would you please improve this situation because Japanese users may misunderstand the release date when referring to the Japanese page?

**Comment by mak-adobe** [comment]
@kaketari 対応可能か調査しています。少しお待ちください。

**Comment by mak-adobe** [comment]
@kaketari だいぶお時間いただいてしまい申し訳ありません。G11N-16031 のチケットで検討しております。

**Comment by mak-adobe** [comment]
@kaketari 検討の結果、タイムゾーンであるPTを表記するという現在のガイドラインの方針を継続することになりました。ご報告をありがとうございました。
