### ISSUE TITLE
翻訳エラー：「すなわち」

### ISSUE THREAD

**Issue by nozokada** [AdobeDocs/marketo.ja-JP#12]
Issue in ./help/marketo/product-docs/administration/marketo-custom-objects/create-marketo-custom-objects.md

【現在の翻訳】Marketo カスタムオブジェクトの入力は、リストのインポート、すなわち API 経由でのみ可能です。
【正しい翻訳】 Marketo カスタムオブジェクトの入力は、リストのインポート、または API 経由でのみ可能です。
【原文】You can only populate Marketo Custom Objects via a list import, or the API.

**Comment by mak-adobe** [comment]
@nozokada ありがとうございます。G11N-13002 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@nozokada 修正が完了しました。ご確認お願いします。
