### ISSUE TITLE
翻訳エラー：「動的チャットのチャットソース」

### ISSUE THREAD

**Issue by nozokada** [AdobeDocs/marketo.ja-JP#13]
Issue in ./help/marketo/release-notes/current.md

【原文】
Chat Source for Dynamic Chat

【現在の訳】
動的チャットのチャットソース

【正しい訳】
Dynamic Chat のチャットソース

よろしくいお願いします。

**Comment by mak-adobe** [comment]
@nozokada ご報告ありがとうございます。G11N-13190 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
お待たせしました。7月のリリースノートの修正が完了しました。
