### ISSUE TITLE
”追加 Munchkin Web サイトへのトラッキングコード” ページの日本語自動翻訳修正依頼

### ISSUE THREAD

**Issue by mihazeya** [AdobeDocs/marketo.ja-JP#14]
Issue in ./help/marketo/product-docs/administration/additional-integrations/add-munchkin-tracking-code-to-your-website.md

上記ページの日本語自動翻訳の精度が低い。
例として、件名および小見出しで添付画像のように主語述語が入れ替わっている。他の文章も不自然な個所が多いので査読して修正してほしい。

例) 件名
追加 Munchkin Web サイトへのトラッキングコード

<img width="565" alt="image" src="https://github.com/AdobeDocs/marketo.ja-JP/assets/86053453/c3ffe0b0-c383-49ae-90fb-a4442e34529f">

<img width="576" alt="image" src="https://github.com/AdobeDocs/marketo.ja-JP/assets/86053453/b876e554-ac69-476a-82d1-f32642ac07af">

**Comment by mak-adobe** [comment]
ご報告ありがとうございます。G11N-13191 のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@mihazeya 大変お待たせしました。修正が完了しました。
