### ISSUE TITLE
日本語の翻訳が間違っている

### ISSUE THREAD

**Issue by Yamdayoko** [AdobeDocs/marketo.ja-JP#15]
Issue in ./help/marketo/product-docs/administration/marketo-custom-objects/add-marketo-custom-object-fields.md
Japanese translation for the folloing NOTE is incorrect.
https://experienceleague.adobe.com/docs/marketo/using/product-docs/administration/marketo-custom-objects/add-marketo-custom-object-fields.html?lang=ja
===
NOTE
The API name can be edited only until it’s approved.
===
Currently it says as follows.
===
メモ
API 名は、承認されるまで編集できません。
===
The correct translation will be as follows.
===
メモ
API 名は、一度承認されると編集できません。
===

**Comment by mak-adobe** [comment]
ありがとうございます。G11N-13353のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@Yamdayoko お待たせいたしました。修正が完了しました。
