### ISSUE TITLE
翻訳エラー：「アトリビューション設定」

### ISSUE THREAD

**Issue by TomomiSasagawa** [AdobeDocs/marketo.ja-JP#16]
Issue in ./help/marketo/product-docs/administration/settings/change-attribution-settings-for-analytics.md

▶https://experienceleague.adobe.com/docs/marketo/using/product-docs/administration/settings/change-attribution-settings-for-analytics.html?lang=ja
【原文】
 Attribution Settings

【現在の訳】
アトリビューション設定

【正しい訳】
属性設定

よろしくいお願いします。

**Comment by mak-adobe** [comment]
@TomomiSasagawa ありがとうございます。 G11N-13839 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@TomomiSasagawa 修正が完了しました。ご協力ありがとうございました。
