### ISSUE TITLE
翻訳エラー：リードレポートをセグメント別にグループ化する

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#17]
Issue in ./help/marketo/product-docs/personalization/segmentation-and-snippets/segmentation/group-person-reports-by-segment.md

【現在の翻訳】リードレポート
【正しい翻訳】顧客の実績レポート
【原文】Person Reports

【現在の翻訳】4. リードのグループ化基準​ダイアログで、テキストボックスに「セグメント化」と入力し始めます。次の場合に​セグメント化​見出しが表示されたら、見出しの下のリストから 1 つ選択します。
【正しい翻訳】 4. リードのグループ化基準​ダイアログで、テキストボックスに「segmentation」と入力し始めます。次の場合に​セグメンテーション​見出しが表示されたら、見出しの下のリストから 1 つ選択します。
【原文】4. In the Group People by dialog, start typing ‘Segmentation’ in the text box. When the Segmentations heading appears, select one from the list below the heading.

**Comment by mak-adobe** [comment]
@amorishi ありがとうございます。 G11N-13829 のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しましたが、ページのタイトルが「をセグメント別にグループ化する」と不完全な日本語になってしまったので、修正を依頼中です。もう少しお待ちください。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご協力ありがとうございました。
