### ISSUE TITLE
翻訳エラー：メールレポートをセグメント化別にグループ化する

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#18]
Issue in ./help/marketo/product-docs/personalization/segmentation-and-snippets/segmentation/group-email-reports-by-segmentations.md

【現在の翻訳】セグメント化
【正しい翻訳】セグメンテーション
【原文】Segmentations

【現在の翻訳】3. 「設定」タブをクリックして、セグメント化別にグループ化」をドラッグします。
【正しい翻訳】3. 「設定」タブをクリックして、「セグメンテーション別」をドラッグします。
【原文】3. Click the Setup tab and drag over Group by Segmentations.

**Comment by mak-adobe** [comment]
@amorishi ありがとうございます。 G11N-13830 のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了したのですが、「セグメンテーション別」ではなく「グループ - セグメンテーション別」へと修正されました。この文言がUIと合致するのか確認中です。日本語UIではどちらが正解か、もし確認可能でしたら確認いただけると幸いです。

**Comment by amorishi** [comment]
@mak-adobe 
ご対応ありがとうございます。日本語UIでは「セグメンテーション別」となっておりました。参考に画面キャプチャを添付いたします。
![image](https://github.com/AdobeDocs/marketo.ja-JP/assets/133627566/2b67ad7b-83d4-4057-a9ea-f02bea55eb48)

**Comment by mak-adobe** [comment]
@amorishi 早速のご確認ありがとうございました。修正を調整中です。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご協力ありがとうございました。
