### ISSUE TITLE
翻訳エラー：成功パス分析の使用

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#19]
Issue in ./help/marketo/product-docs/reporting/revenue-cycle-analytics/revenue-cycle-models/using-the-success-path-analyzer.md

【現在の翻訳】「インフロー」
【正しい翻訳】「流入」
【原文】In Flow 

【現在の翻訳】「アウトフロー」
【正しい翻訳】「流出」
【原文】Out Flow

【現在の翻訳】「平均時間」
【正しい翻訳】「平均日数」
【原文】Avg Time

![image](https://github.com/AdobeDocs/marketo.ja-JP/assets/133627566/e6ec9f1d-5899-4efd-8986-3e17e3969797)

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご報告ありがとうございました。
