### ISSUE TITLE
動的チャット -> ダイナミックチャット

### ISSUE THREAD

**Issue by nozokada** [AdobeDocs/marketo.ja-JP#2]
Issue in ./help/marketo/release-notes/current.md

「動的チャット」を「ダイナミックチャット」に修正してください。よろしくお願いします。

**Comment by mak-adobe** [comment]
ありがとうございます。調査・対応を開始しました。

**Comment by mak-adobe** [comment]
@nozokada G11N-12450のチケットで対応中です。

**Comment by mak-adobe** [comment]
@nozokada 協議の結果、「Dynamic Chat」と英語表記にすることになりました。

**Comment by mak-adobe** [comment]
@nozokada  修正対象コンテンツが過去のリリースのページへ移動したため、再度調整しております。

**Comment by mak-adobe** [comment]
@nozokada 大変お待たせしました。修正が完了しました。
https://experienceleague.adobe.com/docs/marketo/using/release-notes/previous-releases/2023/release-notes-mar-23.html?lang=ja
