### ISSUE TITLE
翻訳エラー：キャンペーンのリクエスト

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#20]
Issue in ./help/marketo/product-docs/core-marketo-concepts/smart-campaigns/flow-actions/request-campaign.md
【現在の翻訳】「特別」
【正しい翻訳】「特殊」
【原文】Special

**Comment by mak-adobe** [comment]
@amorishi ありがとうございます。「People」の訳を「人物」から「顧客」へ修正するのも追加し、 G11N-13931  のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご協力ありがとうございました。
