### ISSUE TITLE
Marketo サポート{target=“_blank”}にお問い合わせ下さい。　おそらくプレースホルダーが間違っている

### ISSUE THREAD

**Issue by mkawachi** [AdobeDocs/marketo.ja-JP#21]
Issue in ./help/marketo/product-docs/core-marketo-concepts/smart-lists-and-static-lists/creating-a-smart-list/best-practices-for-smart-lists.md

こちらのページ内の以下の{target=“_blank”}は間違い。適切なリンクなりプレースホルダーとして動作するべき。

Marketo サポート{target=“_blank”}にお問い合わせ下さい。

**Comment by mak-adobe** [comment]
@mkawachi ありがとうございます。 G11N-14073 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@mkawachi 修正が完了しました。ご協力ありがとうございました。

**Comment by mkawachi** [comment]
ありがとうございます。
