### ISSUE TITLE
演算子が翻訳されていない

### ISSUE THREAD

**Issue by mkawachi** [AdobeDocs/marketo.ja-JP#22]
Issue in ./help/marketo/product-docs/core-marketo-concepts/smart-lists-and-static-lists/creating-a-smart-list/best-practices-for-smart-lists.md

> 負の演算子よりも正の演算子を使用する -「**not**」フィルターは使用できますが、インスタンス内のデータセット全体が検索される必要があり、非常に時間がかかる場合があります。正の「**is**」フィルターでは、より効果的な検索アルゴリズムを活用できます。
> 「**contains**」を避ける - 部分的なデータのみがある場合、「**starts with**」修飾子は「**contains**」よりもはるかに高速に結果を生成します。「**Is**」はさらに速く実行されます。複数の値で「**contains**」を使用することは避けます。2 つが一緒になると、キャンペーンはさらに遅くなる可能性があります。

上記演算子は、Marketo Engage上で翻訳されているため、ドキュメントでも翻訳されているべき。
ちなみに他の説明部分では翻訳されているので、なぜここだけ英語なのかも疑問です。

**Comment by mak-adobe** [comment]
@mkawachi ありがとうございます。 G11N-14074 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@mkawachi 修正が完了しました。ご協力ありがとうございました。

**Comment by mkawachi** [comment]
ありがとうございます。
