### ISSUE TITLE
翻訳エラー：Marketo のプロトコルの設定／手順 4:DMARC のセットアップ

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#23]
Issue in ./help/marketo/getting-started/setup/configure-protocols-for-marketo.md
【現在の翻訳】
三。
四位

【正しい翻訳】
3.
4.
【原文】
III. 
IV.
<img width="319" alt="image" src="https://github.com/AdobeDocs/marketo.ja-JP/assets/133627566/b0947a33-b785-419f-a161-b2d95c04dae8">

------------------------------------
【現在の翻訳】
~に対して
アドキム
【正しい翻訳】
fo
adkim
【原文】
fo
adkim
<img width="270" alt="image" src="https://github.com/AdobeDocs/marketo.ja-JP/assets/133627566/2284f717-37a1-422b-9b93-6e9d9611219d">

**Comment by mak-adobe** [comment]
@amorishi ありがとうございます。G11N-14186 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@amorishi ほぼ修正されましたが、数字が III, IVとローマ数字になっているので、再度修正を依頼しました。もう少々お待ちください。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご報告ありがとうございました。
