### ISSUE TITLE
“Require Proof Key for Code Exchange (PKCE)” checkbox is NOT checked

### ISSUE THREAD

**Issue by YuyaKoyanagawa** [AdobeDocs/marketo.ja-JP#24]
Issue in ./help/marketo/product-docs/crm-sync/salesforce-sync/log-in-using-oauth-2-0.md

`[New Connected App] ページを表示したまま、下にスクロールして、[Require Proof Key for Code Exchange (PKCE)] チェックボックスがオンになっていることを確認します。 NOT オンにすると、設定の妨げになるので、オンにします。
`
と記載されている箇所をもとにSalesforce管理者がオンに変更しましたが、正しくはオフです。
`While still on the New Connected App page, scroll down and make sure the “Require Proof Key for Code Exchange (PKCE)” checkbox is NOT checked, as it would interfere with setup.`

Salesforceの日本語環境では以下の翻訳です。
「サポートされる認証フローに Proof Key for Code Exchange (PKCE) 拡張を要求」
<img width="706" alt="image" src="https://github.com/AdobeDocs/marketo.ja-JP/assets/27201790/1e6fd86a-60d7-411d-ad36-a16893fa07cd">

**Comment by mak-adobe** [comment]
@YuyaKoyanagawa 修正が完了しました。ご協力ありがとうございました。
