### ISSUE TITLE
The title refers to a different product.

### ISSUE THREAD

**Issue by YuyaKoyanagawa** [AdobeDocs/marketo.ja-JP#25]
Issue in ./help/marketo/product-docs/demand-generation/dynamic-chat/analytics.md

The title refers to a different product.
Marketo Measure (formerly Bizible) and DynamicChat are separate products.

<img width="931" alt="image" src="https://github.com/AdobeDocs/marketo.ja-JP/assets/27201790/b295a702-dec8-4413-8468-dbf2eccc1293">

**Comment by mak-adobe** [comment]
@YuyaKoyanagawa ありがとうございます。G11N-14274 のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@YuyaKoyanagawa 修正が完了しました。ご協力ありがとうございました。
