### ISSUE TITLE
翻訳エラー：待機フローステップで日付トークンを使用

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#26]
Issue in ./help/marketo/product-docs/core-marketo-concepts/smart-campaigns/flow-actions/wait/use-a-date-token-in-a-wait-flow-step.md
【現在の翻訳】
1. スマートキャンペーン内 流量 タブをクリックし、
【正しい翻訳】
1. スマートキャンペーン内 フロー タブをクリックし、
【原文】
1. In your Smart Campaign Flow tab, 

![image](https://github.com/AdobeDocs/marketo.ja-JP/assets/133627566/88925676-c5e2-40fd-b33c-b8e53c758bb7)

**Comment by mak-adobe** [comment]
ありがとうございます。 G11N-14327 のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご協力ありがとうございました。
