### ISSUE TITLE
日本語版の「2.「ユーザ＆ロール」をクリックします」で表示されている画像が全く別の画面になっている

### ISSUE THREAD

**Issue by Yamdayoko** [AdobeDocs/marketo.ja-JP#28]
Issue in ./help/marketo/product-docs/core-marketo-concepts/marketing-calendar/understanding-the-calendar/issue-revoke-a-marketing-calendar-license.md
日本語版の「2.「ユーザ＆ロール」をクリックします」で表示されている画像が全く別の画面になっている。

**Comment by mak-adobe** [comment]
@Yamdayoko ありがとうございます。 G11N-14853 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@Yamdayoko 大変お待たせしました。修正が完了しました。
