### ISSUE TITLE
go together like peas and carrotsの日本語訳が直訳になっている

### ISSUE THREAD

**Issue by naoki-kojima25** [AdobeDocs/marketo.ja-JP#29]
原文: Marketo Engage and Salesforce go together like peas and carrots.
日本語訳: Marketo Engageと Salesforce は、豆やニンジンのように一緒に移動します。 

上記のように日本語訳が直訳になっており、意味が理解しにくい状態になっています
一方で、Salesforce連携という重要な記事の冒頭でもあり、読み手の混乱を少なくしたいと考えています
以下の修正案はいかがでしょうか？

修正案: Marketo Engageと Salesforce は密接に連携しています。

https://experienceleague.adobe.com/docs/marketo/using/product-docs/crm-sync/salesforce-sync/understanding-the-salesforce-sync.html?lang=ja

**Comment by mak-adobe** [comment]
@naoki-kojima25 ありがとうございます。 G11N-14966 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@naoki-kojima25 修正が完了しました。ご協力ありがとうございました。
