### ISSUE TITLE
Dynamic Chat is DNT for Japanese.

### ISSUE THREAD

**Issue by mkawachi** [AdobeDocs/marketo.ja-JP#3]
Issue in ./help/marketo/product-docs/demand-generation/dynamic-chat/dynamic-chat-overview.md

Dynamic Chat is translated to "動的チャット". It's a service name, so it should be DNT, Dynamic Chat.

**Comment by yanlicao** [comment]
Kawachi-san, another client said it should be "ダイナミックチャット"
Please refer to https://jira.corp.adobe.com/browse/G11N-12450
Please decide which one is final and we will global fix.

**Comment by mkawachi** [comment]
Hi, I'm confirming this should be DNT or not, with Adobe G11n team. Please wait the action. 
ダイナミックチャット is fine at this point.

**Comment by yanlicao** [comment]
Thanks Kawachi-san. Let me close this ticket for now. We can use https://jira.corp.adobe.com/browse/G11N-12450 to track this term.
