### ISSUE TITLE
3月のリリースノートにて、「対話型フロー」の日本語訳が「対話フロー」「会話フロー」となっている箇所がある

### ISSUE THREAD

**Issue by naoki-kojima25** [AdobeDocs/marketo.ja-JP#30]
3月のリリースノートにて、「対話型フロー」の日本語訳が「対話フロー」「会話フロー」となっている箇所がある
https://experienceleague.adobe.com/docs/marketo/using/release-notes/current.html?lang=ja

**Comment by mak-adobe** [comment]
@naoki-kojima25 ありがとうございます。 G11N-14967 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@naoki-kojima25 大変お待たせしました。修正が完了しております。
（該当ページのURLは以下に変わりました）
https://experienceleague.adobe.com/ja/docs/marketo/using/release-notes/previous-releases/2024/release-notes-mar-24

**Comment by naoki-kojima25** [comment]
@mak-adobe ありがとうございます！修正を確認できました！
