### ISSUE TITLE
Salesforceとの連携について、誤読が発生しうる訳文がある

### ISSUE THREAD

**Issue by naoki-kojima25** [AdobeDocs/marketo.ja-JP#31]
原文:
Marketo Engage doesn’t automatically delete people just because leads were deleted in Salesforce.

現在の機械翻訳:
Marketo Engageは、リードが Salesforce で削除されたので、担当者を自動的に削除しません。

提案: 
Salesforce でリードを削除しても、Marketo Engage が自動的に人物を削除することはありません。

https://experienceleague.adobe.com/docs/marketo/using/product-docs/crm-sync/salesforce-sync/sfdc-sync-details/sfdc-sync-deleting-a-lead-contact.html?lang=ja

**Comment by mak-adobe** [comment]
@naoki-kojima25 ありがとうございます。 G11N-14968 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@naoki-kojima25 大変お待たせしました。修正が完了しました。
