### ISSUE TITLE
Fix Japanese translation on SFDC Sync

### ISSUE THREAD

**Issue by naoki-kojima25** [AdobeDocs/marketo.ja-JP#32]
The machine translation on ExL is unnatural.
Since this information is important to the customer, to I propose a new Japanese translation.
Link: https://experienceleague.adobe.com/ja/docs/marketo/using/product-docs/crm-sync/salesforce-sync/sfdc-sync-details/sfdc-sync-campaign-sync

English: The channel and period cost in Marketo sync to Salesforce as the campaign type and actual cost. This sync is one way, from Marketo to Salesforce.

Current Japanese: The チャネル and period cost Marketoと Salesforce を キャンペーンタイプ および 実費. この同期は、Marketo から Salesforce への 一方向 です。

New Japanese: Marketo で指定されたチャネルと期間原価の金額は、Salesforce キャンペーンの「種別」と「キャンペーンの実費」として同期されます。なお、この同期は Marketo から Salesforce への一方向となります。

Issue in ./help/marketo/product-docs/crm-sync/salesforce-sync/sfdc-sync-details/sfdc-sync-campaign-sync.md

**Comment by mak-adobe** [comment]
@naoki-kojima25 ありがとうございます。G11N-15852 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@naoki-kojima25 もう一つのチケット G11N-15904 で対応しております。もう少しお待ちください。

**Comment by mak-adobe** [comment]
@naoki-kojima25 修正が完了しました。ご協力ありがとうございました。

**Comment by naoki-kojima25** [comment]
@mak-adobe ありがとうございます！大変助かります！

**Comment by naoki-kojima25** [comment]
@mak-adobe 
こちらのチケットの修正が一部不足していたことがわかり、再度修正依頼をさせて頂きたいです🙏
詳細なポイントなので、pull requestの形で連携させて頂きます。ご確認お願いします。
https://github.com/AdobeDocs/marketo.ja-JP/pull/34
