### ISSUE TITLE
fix two strings to match the SFDC terms

### ISSUE THREAD

**Issue by naoki-kojima25** [AdobeDocs/marketo.ja-JP#35]
@mak-adobe
こちらのチケットの修正が一部不足していたことがわかり、再度修正依頼をさせて頂きたいです🙏
詳細なポイントなので、pull requestの形で連携させて頂きます。ご確認お願いします。
https://github.com/AdobeDocs/marketo.ja-JP/pull/34

_Originally posted by @naoki-kojima25 in https://github.com/AdobeDocs/marketo.ja-JP/issues/32#issuecomment-2219555330_

**Comment by mak-adobe** [comment]
@naoki-kojima25 ありがとうございます。 G11N-16792 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@naoki-kojima25 大変お待たせしました。修正が完了しました。ご確認お願いします。

**Comment by naoki-kojima25** [comment]
@mak-adobe 
ご連絡ありがとうございます、無事修正が確認できました！
こちらのrepoに作成したPRはcloseしておきます！
