### ISSUE TITLE
Update use-the-email-program-dashboard.md #36

### ISSUE THREAD

**Issue by naoki-kojima25** [AdobeDocs/marketo.ja-JP#37]
Submitted a fix request as PR.

https://github.com/AdobeDocs/marketo.ja-JP/pull/36

**Comment by mak-adobe** [comment]
@naoki-kojima25 ありがとうございます。 G11N-16859 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@naoki-kojima25 修正が完了しました。ご協力ありがとうございました。
（PRはTranslatorやLinguistを含む現在の翻訳ワークフローでは機能しないので削除お願いします。このGitHubのIssueとしてレポートいただけるとスムーズです。）

**Comment by naoki-kojima25** [comment]
ご修正ありがとうございます！
PRをcloseしました。今後、おっしゃる通りのプロセスで進めようと思います。
変更点が多いなどリクエストが複雑な場合は、PRでのコミュニケーションになる可能性がありますことどうかご容赦ください🙏
