### ISSUE TITLE
日本語誤訳　「2048 年の鍵サイズを推奨します。」

### ISSUE THREAD

**Issue by Yamdayoko** [AdobeDocs/marketo.ja-JP#38]
Issue in ./help/marketo/product-docs/email-marketing/deliverability/set-up-a-custom-dkim-signature.md

Tipの「We recommend a Key Size of 2048.」の日本語の翻訳が、「2048 年の鍵サイズを推奨します。」になっているが、2024はサイズであって都市ではないので、「2048 の鍵サイズを推奨します。」に修正をしてほしいです

**Comment by mak-adobe** [comment]
@Yamdayoko 修正が完了しました。ご協力ありがとうございました。
