### ISSUE TITLE
Fail to translate ”Individual IP address” in Japan/　翻訳エラー Cloud guide for Commerce

### ISSUE THREAD

**Issue by scs36000** [AdobeDocs/marketo.ja-JP#4]
Issue in ./help/marketo/getting-started/setup/configure-protocols-for-marketo.md

At the bottom of the documents, "Individual IP Address" is translated as "個人のIPアドレス"  in Japanese.
The current translation doesn't tell the correct meaning.
"個別のIPアドレス" is better.

Could you mind updating the docs in Japanese?

![Individual IP address](https://github.com/AdobeDocs/marketo.ja-JP/assets/133207994/5498bae7-3c19-4cc7-aca9-bb29a3d8abd4)
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
現在の翻訳　（Current Translation)　　: 個人のIPアドレス
正しい翻訳　（Expected Translation）：個別のIPアドレス
原文（Original String）　　　　　　　: Individual　IP Address
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

**Comment by yanlicao** [comment]
Thank you for your feedback. This is being reviewed and tracked in G11N-12540

**Comment by yanlicao** [comment]
This is fixed now, please check attached screenshot.
Thanks again for your feedback, close this bug for now.
![image](https://github.com/AdobeDocs/marketo.ja-JP/assets/2255096/d8a5132c-0117-4bf1-a1c9-d88f591e2f8b)

**Comment by scs36000** [comment]
I confirm the wrong translation of ”Individual IP address" in Japanese is fixed.
▶https://experienceleague.adobe.com/docs/marketo/using/getting-started-with-marketo/setup/configure-protocols-for-marketo.html?lang=ja#outbound-ip-addresses
I appreciate for your help.
