### ISSUE TITLE
"Treasure Chest" is not translated as "アイディアスペース"

### ISSUE THREAD

**Issue by naoki-kojima25** [AdobeDocs/marketo.ja-JP#40]
Origin: Treasure Chest
Current: 宝箱
Expected: アイディアスペース

Target page: https://github.com/AdobeDocs/marketo.ja-JP/blob/main/help/marketo/release-notes/current.md

Treasure Chest is usually translated as アイディアスペース in Japanese.
I will request the registration of this word to QuickTerm since the word cannot be found.

The definition is admitted in QuickTerm.
https://terms.adobe.com/terminology/search?tenant=Default&termbaseId=10&entryUUID=b37cf76a-3e04-4700-906b-1f56f8eb282b

**Comment by mak-adobe** [comment]
@naoki-kojima25 確認が取れました。G11N-17690 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@naoki-kojima25 修正が完了しました。ご協力ありがとうございました。
