### ISSUE TITLE
翻訳エラー：非ネイティブ MS Dynamics 統合用 Sales Insight

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#5]
Issue in ./help/marketo/product-docs/marketo-sales-insight/sales-insight-for-non-native-ms-dynamics-integrations.md
【現在の翻訳】Salesforce セールスユーザは、Salesforce のリード／取引先責任者を所有する外部ユーザです。
【正しい翻訳】 MS Dynamics セールスユーザは、 MS Dynamics のリード／取引先責任者を所有する外部ユーザです。
【原文】The MS Dynamics Sales User is an external user that owns the Leads/Contacts in MS Dynamics.

**Comment by mak-adobe** [comment]
ご報告ありがとうございます。調査・対応を開始しました。

**Comment by mak-adobe** [comment]
@amorishi  G11N-12565のチケットで対応中です。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご協力ありがとうございました。
