### ISSUE TITLE
翻訳エラー：Web キャンペーンで A/B テストを実施する

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#6]
Issue in ./help/marketo/product-docs/web-personalization/working-with-web-campaigns/ab-test-your-web-campaign.md
【現在の翻訳】自動チューニング
【正しい翻訳】 自動調整
【原文】Auto Tune

![image](https://github.com/AdobeDocs/marketo.ja-JP/assets/133627566/5a175974-9bf9-4bb6-b982-5be0fbb474de)

**Comment by mak-adobe** [comment]
@amorishi ありがとうございます。G11N-12666 のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご協力ありがとうございました。
