### ISSUE TITLE
翻訳エラー：プログラムメンバーカスタムフィールドの同期

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#7]
Issue in ./help/marketo/product-docs/core-marketo-concepts/programs/working-with-programs/program-member-custom-field-sync.md
【現在の翻訳】・の作成 プログラムメンバーカスタムフィールド
【正しい翻訳】 ・プログラムメンバーカスタムフィールドの作成
【原文】Creation of Program Member Custom Fields

**Comment by mak-adobe** [comment]
@amorishi ありがとうございます。G11N-12678のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@amorishi 修正が完了しました。ご協力ありがとうございました。
