### ISSUE TITLE
翻訳エラー： Webhook の作成

### ISSUE THREAD

**Issue by amorishi** [AdobeDocs/marketo.ja-JP#8]
Issue in ./help/marketo/product-docs/administration/additional-integrations/create-a-webhook.md
・1箇所目
【現在の翻訳】の作成 Webhook
【正しい翻訳】 Webhook の作成
【原文】Create a Webhook

・2箇所目
【現在の翻訳】用途 Webhooks サードパーティの web サービスを活用して、テキストメッセージを送信したり、個人データを拡張したりできます。
【正しい翻訳】 Webhook を使うことで、サードパーティの web サービスを活用して、テキストメッセージを送信したり、個人データを拡張したりできます。
【原文】Use Webhooks to take advantage of third-party web services to send text messages, expand person data, and more.

**Comment by mak-adobe** [comment]
@amorishi  ありがとうございます。G11N-12679のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@amorishi 大変お待たせしました。修正が完了しました。
