### ISSUE TITLE
Need to delete "Single Sign-on (SSO) users" specification

### ISSUE THREAD

**Issue by scs36000** [AdobeDocs/marketo.ja-JP#9]
Issue in ./help/marketo/product-docs/administration/users-and-roles/email-verification.md

I think this mail notificatoin is sent to all of the Marketo users, not only "Single Sign-on (SSO) users".
Please check the target of this mail, and update the contents of this document.

Appreciate for your help.

**Comment by mak-adobe** [comment]
@scs36000 レポートありがとうございます。
しかしながら、報告いただいたページでは「SSOユーザーだけに通知メールが送信される」という問題箇所を特定できませんでした。

対象ページ：https://experienceleague.adobe.com/docs/marketo/using/product-docs/administration/users-and-roles/email-verification.html?lang=ja

お手数ですが、該当箇所を具体的にご教示ください。

**Comment by mak-adobe** [comment]
@scs36000 最後のご連絡から期間が経過したため一度クローズさせていただきます。まだ必要な場合は再オープンお願いします。
